<?xml version="1.0" ?> 
<!DOCTYPE template [
  <!ELEMENT condition        (action,x,y,height,width,suffix,required)>
  <!ELEMENT section          (x,y,height,width,suffix,type)>
  <!ELEMENT output           (line)>
  <!ELEMENT action           (#PCDATA)>
  <!ELEMENT x                (#PCDATA)>
  <!ELEMENT y                (#PCDATA)>
  <!ELEMENT width            (#PCDATA)>
  <!ELEMENT height           (#PCDATA)>
  <!ELEMENT suffix           (#PCDATA)>
  <!ELEMENT type             (#PCDATA)>
  <!ELEMENT required         (#PCDATA)>
  <!ELEMENT line     	     (#PCDATA)>
]>
<template title="SCHED1">

  <condition>
    <action>1</action>
    <x>30</x>
    <y>0</y>
    <width>1300</width>
    <height>150</height>
    <suffix>cfi1</suffix>
    <required>SCHEDULE I - EARNED INCOME</required>
  </condition>
  
  <section>
    <x>28</x>
    <y>390</y>
    <width>950</width>
    <height>133</height>
    <suffix>01</suffix>
    <type>1</type>
  </section>
  <section>
      <x>1028</x>
      <y>390</y>
      <width>950</width>
      <height>133</height>
      <suffix>02</suffix>
      <type>1</type>
  </section>
  <section>
      <x>1998</x>
      <y>390</y>
      <width>950</width>
      <height>133</height>
      <suffix>03</suffix>
      <type>1</type>
  </section>
  
  <output>
    <line>01#02#03</line>
  </output>
  
</template>
